de-clawing
Islandora/documentation pull request #1190
Opened 2019-06-26 21:04 UTC by seth-shaw-unlv

**GitHub Issue**: #1082 

# What does this Pull Request do?

Updates a bunch of docs to replace references to Islandora CLAW to Islandora 8. Also includes some Fedora 4-specific language to reference Fedora 4/5. 

# How should this be tested?

* Read
* Critique

# Additional Notes:

I specifically did not address docs/user-documentation/getting-started-with-islandora-claw.md or docs/user-documentation/intro-to-claw.md because it seemed like the change may have been confusing. 

Also, I'm not sure if changing the mvp doc was appropriate since it was spelling out what we were planning to do before it became Islandora 8. I can revert that if ya'll think we should.

# Interested parties
@manez, @dannylamb

2019-06-27 12:14 UTC, manez requested changes

2019-06-27 12:14 UTC, manez commented on CONTRIBUTING.md
> +If you are reading this document then you are interested in contributing to Islandora 8. All contributions are welcome: use-cases, documentation, code, patches, bug reports, feature requests, etc. Yo
If you're going to update CONTRIBUTING.md, can you throw these changes in there too? https://gist.github.com/manez/74b7fdda05cd01186c1d9b471c61b9dc 

I'm going to use that as the template across the board to get them all to match.

2019-06-27 14:43 UTC, seth-shaw-unlv commented on CONTRIBUTING.md
> +If you are reading this document then you are interested in contributing to Islandora 8. All contributions are welcome: use-cases, documentation, code, patches, bug reports, feature requests, etc. Yo
Gladly.

2019-06-28 13:17 UTC, manez approved these changes

2019-06-28 17:37 UTC, merged