DeCLAW the main page
Islandora/documentation pull request #1321
Opened 2019-10-28 15:01 UTC by whikloj

**GitHub Issue**: #1267 and #1319 

# What does this Pull Request do?

Do some more deCLAWing

# How should this be tested?

Make sure I got all the claws.

# Interested parties
@Islandora-CLAW/committers and @manez

2019-10-28 15:10 UTC, manez requested changes

2019-10-28 15:10 UTC, manez commented on README.md
>  * [Jared Whiklo](https://github.com/whikloj)
I [signed up](https://docs.google.com/spreadsheets/d/10KUQGfDP5x4uHnvkVtz8EV_S0pjLFxrJqSYhcMf7-C0) to be a maintainer on this one too (leaving you and Danny listed also seems prudent!)

2019-10-28 18:21 UTC, manez approved these changes

2019-10-29 13:13 UTC, dannylamb approved these changes
:shipit:

2019-10-29 13:13 UTC, merged