New documentation: Objects and Resource Nodes #1040
Islandora/documentation pull request #1340
Opened 2019-11-18 16:32 UTC by manez

**GitHub Issue**: https://github.com/Islandora/documentation/issues/1040

[Original document](https://docs.google.com/document/d/1fKynWjP7d-g16Eh0AMBvWXPnasJie-xEzmzajukhUww/edit?usp=sharing)

# What does this Pull Request do?

Takes the conceptual parts of @alexkent0 's document introducing Islandora 8 from an islandora 7 end-user perspective and makes a new page for our docs. This is the source of the term "resource node."

The original document has a lot of additional content that I left out, as it's covered elsewhere in our documentation, but these conceptual bits are unique. 

All done with Alex's permission and approval.

# What's new?
A page of conceptual documentation and a screenshot. 

# How should this be tested?

Preview, read through, give opinions 😄 

# Additional Notes:
Any additional information that you think would be helpful when reviewing this PR.

# Interested parties
@Islandora/8-x-committers and @alexkent0

2019-11-19 23:40 UTC, librarychik requested changes
Made a number of minor suggested edits.  tagging @Islandora/8-x-committers

2019-11-19 23:40 UTC, librarychik commented on docs/user-documentation/objects_to_resource_nodes.md
> +Another difference from Islandora 7 to 8 is with Islandora objects. In Islandora 7, _objects_ (video files, audio files, PDFs, etc.) were loaded through the user interface, and Datastreams were gener
```suggestion
Another difference between Islandora 7 and 8 are Islandora objects. In Islandora 7, _objects_ (video files, audio files, PDFs, etc.) are loaded through the user interface, and Datastreams are generated automatically. These consist of access and display copies, the metadata, OCH/HOCR, technical metadata, and more. All of these Datastreams are directly connected to the object and accessed through the admin interface. 
```

2019-11-19 23:40 UTC, librarychik commented on docs/user-documentation/objects_to_resource_nodes.md
> +In Islandora 8, the traditional Islandora 7 objects (video files, audio files, etc.) are now _Drupal nodes_. Islandora object nodes are a special kind of Drupal node, distinct from nodes that exist f
```suggestion
In Islandora 8, the traditional Islandora 7 objects (video files, audio files, etc.) are now _Drupal nodes_. Islandora object nodes are a special kind of Drupal node, distinct from nodes that exist for other content types such as a blog post, an article, a page (like the About page on a site), and others. These Islandora objects are still loaded through the interface and described with the data entry form and derivatives are still generated. However, the Datastreams are no longer connected to the original object in the same immutable way. Each of these Datastreams can be manipulated through Drupal by non-developers.  You can create a variety of ways to view this metadata and information related to the objects. Doing so requires knowledge of Drupal 8, but this essentially means that there are many ways to view the metadata and access the related objects in Islandora 8. 
```

2019-11-19 23:40 UTC, librarychik commented on docs/user-documentation/objects_to_resource_nodes.md
> +The elements of a resource node are, typically:
```suggestion
The typical elements of a resource node:
```

2019-11-19 23:40 UTC, librarychik commented on docs/user-documentation/objects_to_resource_nodes.md
> +-   Metadata fields entered in the data entry for, such as:
```suggestion
-   Metadata fields submitted in the data entry, for example:
```

2019-11-19 23:40 UTC, librarychik commented on docs/user-documentation/objects_to_resource_nodes.md
> +    -   Your custom fields you need to describe things the way you want to
```suggestion
    -   Descriptive custom fields
```

2019-11-19 23:40 UTC, librarychik commented on docs/user-documentation/objects_to_resource_nodes.md
> +It is possible to configure all elements of a resource node in Islandora 8. This fact allows full control over how one accesses the node and how they are displayed and discovered online. It also allo
```suggestion
It is possible to configure all elements of a resource node in Islandora 8. This fact allows full control over how one accesses the node and how nodes are displayed and discovered online. It also allows a repository to take full advantage of all third-party Drupal modules, themes, and distributions available.  
```

2019-11-19 23:40 UTC, librarychik commented on docs/user-documentation/objects_to_resource_nodes.md
> +These resource nodes are what the librarian, student, archivist, technician, or general non-developer creates through the data entry form. It is a lot more than just the file (JPEG, .MP3, etc.). This
```suggestion
These resource nodes are what the librarian, student, archivist, technician, or general non-developer creates through the data entry form. It is a lot more than just the file (JPEG, .MP3, etc.). This user is creating the node and elements that make it possible to access, manage, and preserve the resource. Islandora 8 is all about empowering this access to repository resources. It makes it possible to touch and manipulate the file itself and the elements that make it a wholly preserved and shareable digital object. This shift is actually at the core of Digital Asset Management (DAM) and librarianship – making things accessible. Islandora 8 is about doing that through Drupal 8 and the web, making it that much more available, flexible, and viable for the future. It does this by making more elements of what was a traditional DAM object configurable and manageable by more users – _non-developers_. Work is ongoing by the community to increase the ease of use of the admin user interface to make this even more feasible. 
```

2019-11-19 23:40 UTC, librarychik commented on docs/user-documentation/objects_to_resource_nodes.md
> +Management attributes of the resource node help to clarify and manage a resource nodes relationship within the repository and other content. Management attributes define if a node is a resource node,
```suggestion
Management attributes of the resource node help to clarify and manage its relationship within the repository and to other content. Management attributes define if a node is a resource node, which collection it belongs to, the type of resource a node is (image, book, newspaper, etc.), and similar actions. When looking at Drupal functions, the following are examples of management attributes: 
```

2019-11-19 23:40 UTC, librarychik commented on docs/user-documentation/objects_to_resource_nodes.md
> +    -   Default content types available are an article, basic page, repository item, video
```suggestion
    -   Default content types available include article, basic page, repository item, video
```

2019-11-19 23:40 UTC, librarychik commented on docs/user-documentation/objects_to_resource_nodes.md
> +    -   Able to add any content types that are needed to help define the resource node
```suggestion
    -   Ability to add any content type needed to help define the resource node 
```

2019-11-20 12:42 UTC, manez commented
Thank you @librarychik ! The new commits made that super easy 😄

2019-11-25 12:54 UTC, manez commented
@Islandora/8-x-committers I think this one is ready to go in

2019-11-26 20:14 UTC, manez commented
@seth-shaw-unlv or @whikloj can I impose? I need this one merged so I can delete my fork and start over on some different stuff 😅

2019-11-26 20:30 UTC, seth-shaw-unlv approved these changes
As per @manez.

2019-11-26 20:33 UTC, seth-shaw-unlv commented
Ih, wait, this is a @manez pr... let me read through.

2019-11-27 12:57 UTC, whikloj approved these changes
This is all good, my only comment and it can happen later would be that a screenshot where the image viewer is not displaying an error is more polished.

2019-11-27 12:58 UTC, merged

2019-11-27 19:36 UTC, seth-shaw-unlv commented
Thanks for covering me there, @whikloj! I'm out of the office this week and got distracted before I could finish the read-through.