Create: oai-pmh doc
Islandora/documentation pull request #1345
Opened 2019-11-18 22:02 UTC by elizoller

For documentation sprint

# What does this Pull Request do?
Adds an OAI-PMH doc page

# What's new?
Adds an OAI-PMH doc page
- pulled some content from @seth-shaw-unlv 's readme on https://github.com/Islandora/islandora_defaults/tree/8.x-1.x/modules/islandora_oaipmh
- added additional info

# How should this be tested?
- read
- check for typos/unclear wording
- test links
- fix incorrect statements/

# Interested parties
 @Islandora-CLAW/committers @seth-shaw-unlv @joecorall

2019-11-18 22:18 UTC, seth-shaw-unlv commented
@joecorall, I know you merged the plugin-based metadata profiles into the Kent State repo, but when do you expect that will be pulled into the Drupal project repo? It would be good to release that as a version so I can do a quick update to the Islandora sub-module config before we release Islandora 8-1.1.

2019-11-19 22:26 UTC, librarychik approved these changes
A few suggested edits, no big changes

2019-11-19 22:28 UTC, librarychik commented on docs/user-documentation/oai.md
> +If you have [islandora_defaults](https://github.com/Islandora/islandora_defaults) then you'll have the [islandora_oaipmh](https://github.com/Islandora/islandora_defaults/tree/8.x-1.x/modules/islandor
Suggest:
The Drupal feature [islandora_defaults](https://github.com/Islandora/islandora_defaults) includes the [islandora_oaipmh](https://github.com/Islandora/islandora_defaults/tree/8.x-1.x/modules/islandora_oaipmh) module.

2019-11-19 22:36 UTC, librarychik requested changes
sorry, my edits didn't save, trying again.

2019-11-19 22:36 UTC, librarychik commented on docs/user-documentation/oai.md
> +Enabling Islandora OAI-PMH will provide you with
Suggest:
Enabling Islandora OAI-PMH provides:

2019-11-19 22:43 UTC, librarychik commented on docs/user-documentation/oai.md
> +Enabling Islandora OAI-PMH will provide you with
and now tagging according to sprint documentation: @Islandora/8-x-committers

2019-11-20 16:37 UTC, seth-shaw-unlv commented on docs/user-documentation/oai.md
> +The Drupal feature [islandora_defaults](https://github.com/Islandora/islandora_defaults) includes the [islandora_oaipmh](https://github.com/Islandora/islandora_defaults/tree/8.x-1.x/modules/islandora
"The Drupal feature" → "The Drupal module". 

"features" (lowercase) refers to Core Drupal or added module functionality, whereas module refers to a _package_ of functionality.

2019-11-20 17:28 UTC, seth-shaw-unlv commented
@librarychik, any more feedback before we merge this? It looks fine to me.

2019-11-20 17:30 UTC, librarychik commented
Thanks @seth-shaw-unlv, looks good to me! 👍

2019-11-20 17:31 UTC, librarychik approved these changes
Looks good.

2019-11-20 17:34 UTC, seth-shaw-unlv requested changes
Wait! We need this added to the TOC in mkdocs.yml!

2019-11-21 17:58 UTC, seth-shaw-unlv commented
The newest release of rest_oai_pmh uses plugins for the metadata mappings now, so I just issued a PR (linked above) to update the islandora_oaipmh module accordingly. Once that gets in we will need to make some small edits to the docs.

That stated, if you want to go ahead and just update the TOC in mkdocs.yml, @elizoller, we can simply merge this now and I can create a new PR once the module updates are merged.

2019-11-21 19:44 UTC, seth-shaw-unlv approved these changes

2019-11-21 19:44 UTC, merged