Update rdf-mapping.md doc
Islandora/documentation pull request #1585
Opened 2020-08-20 16:31 UTC by elizoller

## Purpose / why

Add documentation for change made in: https://github.com/Islandora/documentation/issues/1581

## What changes were made?
Add documentation

## Verification

Make sure the docs are clear.

## Interested Parties

@Islandora/8-x-committers
@seth-shaw-unlv

2020-08-20 22:03 UTC, seth-shaw-unlv requested changes
It is a bit awkward to transition from a bulleted list to the sub-heading. 

Also, the mapping types runs into the datatype_callback when they are really different creatures.

2020-08-21 01:01 UTC, elizoller commented
I separated it into two sub-headings. does that improve readability?

2020-08-21 13:53 UTC, manez commented on docs/islandora/rdf-mapping.md
> +`mapping_type:`: There are several mapping types which are provided out of the box. One of those being `rel` - standing for relationship. The default, or if one is not provided is `property` meaning
"The default, or if one is not provided is `property` meaning a property." I'm having a little bit of trouble parsing this line. Is "one" a relationship? If so, maybe:

 "The default, or if a relationship is not provided, is `property` meaning a property."

2020-08-21 16:02 UTC, elizoller commented on docs/islandora/rdf-mapping.md
> +`mapping_type:`: There are several mapping types which are provided out of the box. One of those being `rel` - standing for relationship. The default, or if one is not provided is `property` meaning
pushed another commit - is that any clearer?

2020-08-21 17:10 UTC, manez approved these changes

2020-08-21 17:10 UTC, manez commented on docs/islandora/rdf-mapping.md
> +`mapping_type:`: There are several mapping types which are provided out of the box. One of those being `rel` - standing for relationship. The default, or if one is not provided is `property` meaning
Looks good to me

2020-08-24 18:40 UTC, rosiel commented
Hey @seth-shaw-unlv i used Github's "re-request review" because merging was blocked by your requested changes (huh!). Sorry for the multi-ping.

2020-08-24 18:41 UTC, rosiel approved these changes
Looks good to me too.

2020-08-25 17:36 UTC, seth-shaw-unlv approved these changes

2020-08-25 17:36 UTC, seth-shaw-unlv commented
Sorry for the delay! I was out yesterday to help the kids with their first day back to school online.

2020-08-25 17:37 UTC, merged