Add more details about starting up an islandora.
Islandora/documentation pull request #1597
Opened 2020-08-28 15:38 UTC by rosiel

## Purpose / why

The "demo" section was really sparse, and there are several ways to quickly try out an islandora. i know this'll be updated again come ISLE, but I think it's useful to have documented! (todo also: improve the installation section to match/be updated).

## What changes were made?

Replaced a lonely link to the future.islandora.ca sandbox, and a complex way of installing with vagrant (which didn't do what we thought it did, since the islandora base box!) with a more fulsome and up-to-date version, also mention the VMs!

## Verification

Uh, links work? Instructions work? Statements accurate? Etc?

## Interested Parties

@manez @DonRichards  (pinging for interest in documentation! :) ) @dannylamb 

## Related issue:

- this documents #1494.
---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

2020-08-28 19:38 UTC, rosiel commented on docs/index.md
> +If you have Vagrant and Git installed as well as VirtualBox, you can spin up the latest release of Islandora Defaults using the [Islandora Playbook](https://github.com/Islandora-Devops/islandora-play
I just learned, in making #1598 , that you also have to change to the dev branch!

2020-08-28 19:58 UTC, manez requested changes
The sandbox and the VM both have some extra bells and whistles beyond Defaults, which we should probably mention so folks don't expect them in the ISLE or Ansible builds where they don't show up.

2020-08-28 19:58 UTC, manez commented on docs/index.md
> +To try Islandora without installing anything, visit [http://future.islandora.ca/](http://future.islandora.ca/). Anyone can log in to this sandbox as an administrator (credentials are below and on the
Add "This sandbox also demonstrates some Drupal contrib modules that are not standard in Islandora, such as View Bulk Edit, which powers the Batch Edit Page."

2020-08-28 19:58 UTC, manez commented on docs/index.md
> +To try Islandora locally, you can download and run the latest [community sandbox VM image](https://islandora.ca/try). This requires installing VirtualBox or another virtualization provider. This also
Add "along with sample content, Views, Blocks, and Drupal contributed modules and themes, to enhance its role as a sandbox."

2020-08-31 13:16 UTC, manez commented on docs/index.md
> +To try Islandora without installing anything, visit [http://future.islandora.ca/](http://future.islandora.ca/). Anyone can log in to this sandbox as an administrator (credentials are below and on the
Sorry, typo in my suggestion earlier. The module is called "Views Bulk Edit" not "View Bulk Edit"

2020-08-31 19:18 UTC, manez approved these changes

2020-08-31 19:19 UTC, manez commented
Tested the instructions and reviewed the wording. All good!

2020-08-31 19:19 UTC, merged