Update installation docs for Houdini differences
Islandora/documentation pull request #1782
Opened 2021-03-18 01:49 UTC by whikloj

## Purpose / why

The Houdini microservice uses Symfony (and has for a while) which is configured differently then the Silex microservices.

See https://github.com/Islandora/documentation/issues/1493

## What changes were made?

Updated the manual installation documentation to specify the new config files that are changed

## Verification

Documentation now shows the actual configuration files located in the Houdini microservice.

## Interested Parties

@Islandora/8-x-committers

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?
* [ ] Does this PR update the _last updated on_ date on the documentation page?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

2021-03-19 14:20 UTC, joshdentremont requested changes
Hi @whikloj you have the path in the apache config set to /var/www/html/Crayfish, but the rest of the instructions have crayfish at /opt/crayfish.

Otherwise, these changes are working. Thanks for the update.

2021-04-15 21:16 UTC, seth-shaw-unlv requested changes
Only a minor fix for comments in the houdini config file, then we are 👍

2021-04-15 21:16 UTC, seth-shaw-unlv commented on docs/installation/manual/installing_crayfish.md
> +\# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
These lines shouldn't start with a `\`.

2021-04-20 18:20 UTC, whikloj commented
@seth-shaw-unlv I have made the requested updates. Let me know if there is anything I missed.

2021-04-20 19:08 UTC, seth-shaw-unlv approved these changes
👍

2021-04-20 19:13 UTC, seth-shaw-unlv commented
@dannylamb, Travis is [choking on the new pip install command](https://travis-ci.com/github/Islandora/documentation/builds/223654969#L250-L251). Do we try to fix this now, or should I just merge this as is and we address Travis later.

2021-04-21 13:02 UTC, dannylamb commented
I'll go ahead and merge it.  I'm not entirely sure why that token is failing, but I'll look into it.  Totally orthogonal to this, so let's :rocket:

2021-04-21 13:02 UTC, merged