Rosiel audit 8
Islandora/documentation pull request #2084
Opened 2022-04-08 14:11 UTC by rosiel

## Purpose / why

Islandora 8 appears a lot in the documentation

## What changes were made?

going through some pages to remove "Islandora 8" and replace it with "Islandora" vs Legacy.

## Verification

Does this still make sense?

## Interested Parties

> _**Replace this text** - Name some folks who may be interested, if documentation related mention @Islandora/documentation, or, if unsure, @Islandora/8-x-committers_

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

2022-04-08 17:09 UTC, seth-shaw-unlv requested changes
Just one little nit-pick, we should be consistent using "Markdown" (this is the form used by [the original creator](https://daringfireball.net/projects/markdown/)) instead of "MarkDown".

Otherwise, this all looks good to me.

2022-04-08 17:53 UTC, rosiel commented
> Just one little nit-pick, we should be consistent using "Markdown" (this is the form used by [the original creator](https://daringfireball.net/projects/markdown/)) instead of "MarkDown".
> 
> Otherwise, this all looks good to me.

Don't get me started on OpenSeadragon...

2022-04-08 17:58 UTC, seth-shaw-unlv approved these changes

2022-04-08 17:58 UTC, seth-shaw-unlv commented
So far so good.

2022-04-08 20:25 UTC, rosiel commented
There are a lot of files to go but I'm going to trim this here and do further PRs for the next ones. (advice would be welcomed, too. It's so tempting to proofread while I have the files open but I might have to stop in the name of getting it done)

2022-04-08 21:05 UTC, ysuarez commented on docs/contributing/editing-docs.md
> +- be willing to learn with [Markdown](http://en.wikipedia.org/wiki/Markdown) - a good [Markdown cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) can help.
Did you mean to leave the word "with" in line 18? I can make my own PR to fix that and run a CLI spellchecker while I am at it.

2022-04-08 21:12 UTC, ysuarez commented
Should we add entries in the glossary for "Islandora Legacy" and/or "Islandora 8" too to help others with thsi transition in terms?  I can create a new PR for it or try to push to @rosiel PR?

2022-04-10 23:55 UTC, misilot commented
@rosiel I opened a [PR](https://github.com/rosiel/documentation/pull/1) against your branch if you want to take a look at that.

2022-04-11 12:13 UTC, rosiel commented
Thanks Tom. The reason I was doing it manually was for catching things like "Islandora 7 and 8" and leaving "Islandora 8" if it's in the title of a recorded youtube video or presentation. I was also doing a mild sanity check as I went, since this update is going to change the "last edited" date. That's why i stopped at 12 files. Let me bring this back to "Draft" status and pull in your changes.

2022-04-11 12:39 UTC, misilot commented
Oh, sorry!

2022-04-11 13:53 UTC, rosiel commented
Thank you so much @misilot ! Your help was a huge time-saver.  @ysuarez I love the suggestion, and just added it.

2022-04-11 13:57 UTC, misilot commented
Glad it was was helpful in the end! Sorry you had to change "OpenSeadragon" back to "Open Seadragon".  I had gone with the spelling/formatting from https://openseadragon.github.io/

2022-04-11 14:06 UTC, rosiel commented
That's correct. But as docs, I think they should be descriptive of what the user sees in the UI. That's why I was careful to leave the module name and file formatter as OpenSeadragon while the Context, Media Display Mode, Node Display Mode, and Taxonomy Term, are all as they appear, wrongly, Open Seadragon.

2022-04-13 19:58 UTC, seth-shaw-unlv commented on docs/contributing/committers.md
> +Islandora is open source and released under MIT and GPLv2 licenses. The software and associated documentation is developed collectively by a community of contributors and committers. All interested c
Nit-pick: missing a period at the end of the paragraph.

2022-04-13 20:03 UTC, seth-shaw-unlv commented on docs/installation/docker-troubleshooting.md
> +If you get a white screen with a 504 Bad Gateway error, this means your containers haven't finished initializing themselves yet.  If you've waiting an appropriate amount of time (2-5 minutes), then t
There shouldn't be a space between "`" and "docker".

2022-04-13 21:11 UTC, seth-shaw-unlv commented
@rosiel , just two small adjustments then 👍.

2022-04-13 21:20 UTC, misilot commented
@seth-shaw-unlv I made the changes if you want to review at https://github.com/rosiel/documentation/pull/2

2022-04-13 22:06 UTC, seth-shaw-unlv commented
That is one way to do it.

2022-04-13 22:07 UTC, merged