St customizations
Islandora/documentation pull request #2312
Opened 2024-05-31 17:40 UTC by joshdentremont

## Purpose / why
Adding information about customizing your site template sites

## What changes were made?
Added a new page with some empty sections that need to be filled in. Some of these are issues that were identified here: https://github.com/Islandora/documentation/issues/2286

## Verification
These sections should be filled in then tested

## Interested Parties
* @Islandora/documentation
* @Islandora/committers

## Checklist

### Pull-request Reviewer
Pull-request reviewer should ensure the following:

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?

### Person Merging
The person merging should ensure the following:

* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

2025-07-24 12:17 UTC, joecorall commented on docs/installation/docker/site-template/customizations.md
> +If you do this, you can remove the fcrepo URL from your DNS records.
```suggestion
If you do this, you can remove the fcrepo domain from your DNS records.
```

2025-07-24 12:22 UTC, joecorall commented on docs/installation/docker/site-template/customizations.md
> +You can modify how nginx handles certain user agents by modifying `/etc/nginx/shared/drupal.defaults.conf` inside your Drupal container. For example, by adding:
I think we should add some guidance here on how to do this.

We should utilize [buildkit's nginx conf](https://github.com/Islandora-Devops/isle-buildkit/blob/bd54c1a1070ab92ddc5bc63e0e062fbfc754a4a2/nginx/rootfs/etc/confd/templates/nginx.conf.tmpl#L168) that includes rules from any `*.conf` file in `/etc/nginx/http.d/` in the drupal container. So IMO the guidance should be to bind mount a new file in that location and/or add that to your Dockerfile build

2025-07-24 12:27 UTC, joecorall commented on docs/installation/docker/site-template/customizations.md
> +You can modify how nginx handles certain user agents by modifying `/etc/nginx/shared/drupal.defaults.conf` inside your Drupal container. For example, by adding:
In fact, I think this is such a vital part of having a web property available on the internet we should probably just put this rule into the dockerfile in site template with a conf file in that directory so people can edit it

2025-07-24 12:29 UTC, joecorall commented on docs/installation/docker/site-template/customizations.md
> +if ($http_user_agent ~ (Bytespider|ClaudeBot|Sogou|SemrushBot|AcademicBotRTU|PetalBot|GPTBot|DataForSeoBot|test-bot) ) {
These are some other bots I've added after they proved to ignore robots.txt in the wild

```suggestion
if ($http_user_agent ~ (OAI-SearchBot|ChatGPT|Scrapy|ImagesiftBot|YandexBot|Bytespider|ClaudeBot|Sogou|SemrushBot|AcademicBotRTU|PetalBot|GPTBot|DataForSeoBot|test-bot) ) {
```

2025-07-24 13:09 UTC, joecorall commented on docs/installation/docker/site-template/customizations.md
> +You can modify how nginx handles certain user agents by modifying `/etc/nginx/shared/drupal.defaults.conf` inside your Drupal container. For example, by adding:
Actually making the regex an env var in isle-buildkit might be the best option

2025-10-23 13:06 UTC, joshdentremont commented
Should we merge this as is, then create an issue to make Joe's proposed changes?

2025-10-23 14:06 UTC, joecorall commented on docs/installation/docker/site-template/customizations.md
> +You can modify how nginx handles certain user agents by modifying `/etc/nginx/shared/drupal.defaults.conf` inside your Drupal container. For example, by adding:
out of scope of this PR

2025-10-23 14:08 UTC, joecorall commented on docs/installation/docker/site-template/customizations.md
> +You can modify how nginx handles certain user agents by modifying `/etc/nginx/shared/drupal.defaults.conf` inside your Drupal container. For example, by adding:
we should just tell people to add a new conf file with this instead of modifying the existing conf. By default, nginx loads all `*.conf` in `/etc/nginx/http.d`

https://github.com/Islandora-Devops/isle-buildkit/blob/main/nginx/rootfs/etc/confd/templates/nginx.conf.tmpl#L167-L168

2025-10-23 14:08 UTC, joecorall requested changes
One comment then I think this is good to merge

2025-10-23 14:11 UTC, joecorall commented on docs/installation/docker/site-template/customizations.md
> +You can modify how nginx handles certain user agents by modifying `/etc/nginx/shared/drupal.defaults.conf` inside your Drupal container. For example, by adding:
Actually. that won't work since it expects a `server {}` directive. I just think we shouldn't be telling people to edit existing conf files so we need to come up with a better solution

2025-10-29 18:48 UTC, joecorall approved these changes

2025-10-29 18:49 UTC, merged